# Generated by Django 4.1.6 on 2023-03-03 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allclubs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clubs',
            name='numero_club',
        ),
        migrations.AlterField(
            model_name='clubs',
            name='nombre',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='clubs',
            name='sede',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
